package com.webtest.icloud.iwork;

public class iCloudConstants 
{
	    public static String downloadFormatInPdf = "Pdf";
	    public static String applicationPages = "pages";
	    public static String applicationKeynote = "keynote";
	    public static String applicationNumbers = "numbers";
	    public static String keynoteExtension = "key";
	    public static String MacOsX = "Mac OS X";
	    public static String firefoxBrowser = "Firefox";
	    public static String googleChromeBrowser = "Googlechrome";
	    public static String internetExplorerBrowser = "Internetexplorer";
	    public static String safari = "Safari";
	    public static char underScore = '_';
	    public static char dot = '.';
	    public static String spaceReplacerInDocumentName = "%20";
	    public static String documentNamesdelimiter = ",";
		public static String valueToSetForParameter = "$";
		public static long convertFileSizeFromBytesToKb = 1024;
		public static String icUserNameTextbox = "//input[@aria-label='Apple ID']";
		public static String icPasswordTextbox = "//input[@aria-label='Password']";
		public static String icBadgeContainer = "//div[@class='atv3 sc-view sc-container-view badge-container-view front']";
		public static String icBadgeAuth = "//div[contains(@class,'sc-view auth-ui-view')]";
		public static String icDevSignIn = "//*[@class='atv3 sc-view auth-ui-view']";
		//"//div[text()=\"Sign In\"]";
		public static String icUserNameTextboxDescription = "icUserNameTextbox";
		public static String icLoginButton = "//div[@title='Sign In']";
		public static String icDevSignInDescription = "icDevSignIn";
		public static String icOKButton = "//label[text()='OK']";
		public static String ME_DOMAIN_NAME = "@me.com";
		public static String ICLOUD_DOMAIN_NAME = "@icloud.com";
		public static String EMPTY_STRING = "";
		public static String iCloudHomeScreenIcon = "//*[@class='img app-switcher']";
		//public static String icCloudLink = "/html/body/div[3]/div[2]/div[6]";
		public static String icCloudLink = "//div[@class='img app-switcher']";
				//"//*[@class='atv3 sc-view sc-button-view sc-image-button-view image-button sc-regular-size no-min-width']";		
		public static String icCloudLinkDescription = "iCloud link";
		public static String icLogoutLink = "//*[@class='atv3 square sc-view sc-button-view signout-button']";
		public static String icLogoutLinkDescription = "Gilligan Logout";
		//public static String icLogout = //"//div[text()='Sign Out']";
		public static String icLogout = "//div[@class='atv3 square sc-view sc-button-view signout-button']"; 
		//"//*[text()='Sign Out']";	"//div[@class='atv3 square sc-view sc-button-view signout-button' and text()='Sign Out']"; 	
		public static String iWorkIcon = "//img[contains(@src,'mobile_documents_icon')]";
		public static String iWorkIconDescription = "iWorkIcon";
		//public static String iFrame = "/html/body/div/div/iframe";
		public static String iFrame = "//*[@class='atv3 sc-view sc-scroll-view documents-scrollview']";
		//public static String tabFrame = "//div[@class='atv3 sc-view sc-collection-view sc-list-view sc-grid-view collection']";
		//public static String tabFrame = "//div[@class='atv3 iwork-titlebar sc-view sc-label-view label __AUTO__']";
		//public static String tabFrame = "//*[@class='atv3 sc-view iwork-dock']";
		public static String iFrameDescription = "The parent frame containing all the tabs";
		public static String keynoteTab = "//label[text()='Keynote']";//"//div[1]/label";
		//public static String keynoteTab = "//div[@class='atv3 iwork-toolbar sc-view sc-segment-view sc-static-layout segment sc-first-segment sc-segment-0 sc-regular-size']";
		public static String keynoteTabDescription = "Keynote tab in the frame";
		public static String pagesTab = "//label[text()='Pages']";
		//public static String pagesTab = "//div[@class='atv3 iwork-toolbar sc-view sc-segment-view sc-static-layout segment sc-middle-segment sc-segment-1 sc-regular-size']";
		public static String pagesTabDescription = "Pages tab in the frame";
		public static String numbersTab = "//label[text()='Numbers']";	
		//public static String numbersTab = "//div[@class='atv3 iwork-toolbar sc-view sc-segment-view sc-static-layout segment sc-middle-segment sc-segment-2 sc-regular-size']";		
		public static String numbersTabDescription = "Numbers tab in the frame";
		public static String actionMenu = "//div[@class='img action-menu']";
		public static String helpMenu = "//div[@class='img help-menu']";
		public static String redoIcon = "//div[@class='img redo-icon']";
		public static String undoIcon = "//div[@class='img undo-icon']";


		public static String actionMenuDescription = "Gear Menu for document";
		public static String uploadDocumentButton = "";
		public static String uploadDocumentButtonDescription = "Upload document link";
		public static String waitForFrame = "20000";
		public static String spinningImage = "//div[11]/img";
		public static String spinningDocSelectionImage = "//*[@class='clickable status updating']/div/div";
		public static String docOpenSpinner = "//*[@class='spinner']";
		public static String docEditCloseSpinner = "//*[@class='clickable status uploading']";
		public static String editPagesLoad = "//div[@class='apple_logo']";
		
		//public static String docCount = "/html/body/div[2]/div[3]/div[2]/div/div[4]/div"; Previous
		//public static String docCount_end = "]/div"; Previouse
		public static String docCount = "//*[@class='atv3 sc-view sc-collection-view sc-list-view sc-grid-view collection']/div";
		public static String docCount_end = "]";
		public static String templateChooseButton = "//label[text()='Choose']";
		public static String documentToDeleteInPagesTab = "//img[contains(@src,'uploaded_pages')]";
		public static String documentToDeleteDescription = "Document to delete";
		public static String deleteOptionClickInPagesTab = "";
		public static String deleteOptionClickDescription = "Delete option";
		public static String downloadOptionGear = "//*[@class='atv3 sc-view sc-menu-item focus']";
		
		public static String selectFirstDoc = "//div[@class='preview clickable preview-img select-border']";
		public static String downloadDocInPagesTab = "//img[contains(@src,'$')]";
		public static String downloadDocInPagesTabDescription = "Document in 2nd position in Pages tab to download";
		public static String downloadArrowDescription = "Download arrow to downlaod the doc";
		public static String downloadArrowForDownloadDocInPagesTab = "//label[text()='Download']";
		public static String exportFormatDescription = "Export format options";
		public static String downloadToPagesFormatInPagesTab = "";
		public static String downloadToPDFFormatInPagesTab = "";
		public static String downloadToWordFormatInPagesTab = "";
		public static String renameFolderClickInPagesTab = "//span[contains(text(),'$')]";
		public static String renameFolderClickDescription = "Folder in 1st position to rename";
		public static String savingTypingRenameTextInFolderInPagesTab = "";
		public static String savingTypingRenameTextInFolderDescription = "";
		public static String renameTextInFolderInPagesTab = "//div[contains(text(),'$')]";
		public static String deleteFolderClickInPagesTab = "//div[@class='folder-img clickable']";
		public static String renameTextInFolderDescription = "Old name of folder to rename";
		public static String documentToDeleteInDeleteFolderInPagesTab = "//img[contains(@class,'preview-img select-border') and contains(@src,'$')]";
		public static String deleteOptionClickToDeleteDocumentsInDeleteFolderInPagesTab = "";
		public static String deleteOptionClickInKeynoteTab = "";
		public static String deleteFolderClickInKeynoteTab = "//div[@class='folder-img clickable']";
		public static String deleteFolderClickDescription = "Folder in 1st position to delete";
		public static String renameFolderClickInKeynoteTab = "//span[contains(text(),'$')]";
		public static String renameTextInFolderInKeynoteTab = "//div[contains(text(),'$')]";
		public static String typingRenameTextInFolder = "//input[@type='text']";
		public static String typingRenameTextInFolderDescription = "Text Field to enter new name";
		public static String savingTypingRenameTextInFolderInKeynoteTab = "";
		public static String documentToDeleteInDeleteFolderInKeynoteTab = "//img[contains(@class,'preview-img select-border') and contains(@src,'$')]";
		public static String deleteOptionClickToDeleteDocumentsInDeleteFolderInKeynoteTab = "";
		public static String downloadDocInKeynoteTab = "//img[contains(@src,'$')]";
		public static String downloadDocInKeynoteTabDescription = "Document in 2nd position in Keynote tab to download";
		public static String downloadArrowForDownloadDocInKeynoteTab = "//label[text()='Download']";
		public static String downloadToKeynoteFormatInKeynoteTab = "";
		public static String downloadToPDFFormatInKeynoteTab = "";
		public static String downloadToPowerPointFormatInKeynoteTab = "";
		public static String documentToDeleteInKeynoteTab = "//img[contains(@src,'uploaded_keynote')]";
		public static String deleteOptionClickInNumbersTab = "";
		public static String downloadDocInNumbersTab = "//img[contains(@src,'$')]";
		public static String downloadDocInNumbersTabDescription = "Document in 2nd position in Numbers tab to download";
		public static String downloadArrowForDownloadDocInNumbersTab = "//label[text()='Download']";
		public static String downloadToNumbersFormatInNumbersTab = "";
		public static String downloadToPdfFormatInNumbersTab = "";
		public static String downloadToExcelFormatInNumbersTab = "";
		public static String renameFolderClickInNumbersTab = "//span[contains(text(),'$')]";
		public static String renameTextInFolderInNumbersTab= "//div[contains(text(),'$')]";
		public static String savingTypingRenameTextInFolderInNumbersTab = "";
		public static String documentToDeleteInNumbersTab = "//img[contains(@src,'uploaded_numbers')]";
		public static String deleteFolderClickInNumbersTab = "//div[@class='folder-img clickable']";
		public static String documentToDeleteInDeleteFolderInNumbersTab = "//img[contains(@class,'preview-img select-border') and contains(@src,'$')]";
		public static String deleteOptionClickToDeleteDocumentsInDeleteFolderInNumbersTab = "";
		public static String nonSupportedBrowserPopup = "//label[text()='OK']";
		public static String nonSupportedBrowserPopupDescription = "Non-supported browser pop-up";
				//"/html/body/div[7]/div[2]/div[6]/div[2]/label";
		//public static String docSelection = "//div[@class='clickable status ready']";
		//public static String docSelection = "//*[@class='img-container']/img";
		public static String docSelection = "//*[@class='atv3 sc-view document-image sc-regular-size']";
		public static String docToRename = "//*[@class='renamer click-rename clickable']";
		
		public static String fontTypeDropDown = "//*[@class='gilligan-atv3 gilligan-atv3-extra iwork-theme popup sc-view sc-button-view sc-select-view iw-font-family-select-view button sc-regular-size icon']/label";
		public static String downloadCancel = "//*[@class='atv3 sc-view sc-label-view title-label title label sc-regular-size']";
		public static String uploadBoxComplete = "//*[@class='atv3 sc-view sc-label-view title-label title label sc-regular-size']";
}